apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  annotations:
    compare-options: IgnoreExtraneous
    sync-options: Prune=false
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress-cert
  namespace: istio-ingress
spec:
  secretName: ingress-cert
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - jetstack
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - backstage.172.28.0.3.nip.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer