---
kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: demo
servers: 1
agents: 1
image: rancher/k3s:v1.26.4-k3s1
subnet: "172.18.0.0/16"
options:
  k3d:
    wait: true
    timeout: 1m0s
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

